In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import matplotlib 
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

In [2]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in /opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (1.4.44)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from sqlalchemy) (4.11.3)
Requirement already satisfied: greenlet!=0.4.17; python_version >= "3" and (platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32")))))) in /opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from sqlalchemy) (2.0.1)
Requirement already satisfied: typing-extensions>=3.6.4; python_version < "3.8" in /opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->sqlalchemy) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /opt/anaconda3/envs/PythonData/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->sqlalchemy) (3.7.0)

In [3]:
China_path = 'China_Data/API_CHN_DS2_en_csv_v2_4670670.csv'
USA_path='US_Data/API_USA_DS2_en_csv_v2_4696777.csv'

In [4]:
China_df = pd.read_csv(China_path,skiprows=4)
China_df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,China,CHN,"Intentional homicides, female (per 100,000 fem...",VC.IHR.PSRC.FE.P5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,China,CHN,Battle-related deaths (number of people),VC.BTL.DETH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN
2,China,CHN,High-technology exports (current US$),TX.VAL.TECH.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.938580e+11,6.558970e+11,6.538480e+11,6.522120e+11,5.945210e+11,6.541570e+11,7.313190e+11,7.153030e+11,7.574590e+11,9.423150e+11
3,China,CHN,Merchandise exports to low- and middle-income ...,TX.VAL.MRCH.WR.ZS,NaN,4.469987e+00,NaN,NaN,NaN,NaN,...,8.282854e+00,9.227428e+00,9.743067e+00,1.011144e+01,1.043965e+01,1.075585e+01,1.110849e+01,1.253216e+01,1.285974e+01,NaN
4,China,CHN,Merchandise exports to low- and middle-income ...,TX.VAL.MRCH.R5.ZS,NaN,2.788421e+00,NaN,NaN,NaN,NaN,...,3.440450e+00,3.404582e+00,3.664379e+00,4.136269e+00,4.580569e+00,4.721325e+00,4.726604e+00,4.601396e+00,3.966772e+00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1437,China,CHN,Forest area (% of land area),AG.LND.FRST.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.169660e+01,2.190209e+01,2.210759e+01,2.231309e+01,2.254288e+01,2.274231e+01,2.294174e+01,2.314117e+01,2.334060e+01,NaN
1438,China,CHN,Urban land area where elevation is below 5 met...,AG.LND.EL5M.UR.K2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1439,China,CHN,Land under cereal production (hectares),AG.LND.CREL.HA,NaN,9.055284e+07,8.976151e+07,9.121657e+07,9.289727e+07,9.191049e+07,...,9.287020e+07,9.406441e+07,9.491049e+07,1.035670e+08,1.024424e+08,1.008016e+08,9.969409e+07,9.808224e+07,9.806881e+07,NaN
1440,China,CHN,Agricultural land (% of land area),AG.LND.AGRI.ZS,NaN,3.642005e+01,3.671215e+01,3.701487e+01,3.731747e+01,3.772099e+01,...,5.610783e+01,5.610804e+01,5.609674e+01,5.609020e+01,5.608167e+01,5.607733e+01,5.607707e+01,5.607701e+01,5.607690e+01,NaN
1441,China,CHN,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,5.266100e+04,5.536000e+04,5.965700e+04,6.629000e+04,7.302100e+04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
USA_df = pd.read_csv(USA_path,skiprows=4)
USA_df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
0,United States,USA,"Intentional homicides, female (per 100,000 fem...",VC.IHR.PSRC.FE.P5,NaN,NaN,NaN,NaN,NaN,NaN,...,1.980962e+00,1.976418e+00,2.055732e+00,2.277249e+00,2.249178e+00,2.235675e+00,2.157797e+00,2.601145e+00,NaN,NaN
1,United States,USA,Battle-related deaths (number of people),VC.BTL.DETH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,United States,USA,High-technology exports (current US$),TX.VAL.TECH.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.692224e+11,1.758812e+11,1.752438e+11,1.739217e+11,1.545450e+11,1.538085e+11,1.539235e+11,1.415386e+11,1.692173e+11,NaN
3,United States,USA,Merchandise exports to low- and middle-income ...,TX.VAL.MRCH.WR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,United States,USA,Merchandise exports to low- and middle-income ...,TX.VAL.MRCH.R5.ZS,4.075968,3.397109,4.519800,5.297530,5.123848,4.708710,...,1.644112e+00,1.570116e+00,1.678999e+00,1.794014e+00,2.028991e+00,2.398344e+00,2.477851e+00,2.326888e+00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1437,United States,USA,Average precipitation in depth (mm per year),AG.LND.PRCP.MM,NaN,NaN,715.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7.150000e+02,7.150000e+02,NaN,NaN,NaN,NaN
1438,United States,USA,Land area where elevation is below 5 meters (%...,AG.LND.EL5M.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1439,United States,USA,Rural land area where elevation is below 5 met...,AG.LND.EL5M.RU.K2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1440,United States,USA,Arable land (hectares per person),AG.LND.ARBL.HA.PC,NaN,0.983336,0.949378,0.948912,0.927442,0.910948,...,4.921642e-01,4.902827e-01,4.883881e-01,4.865514e-01,4.851617e-01,4.826143e-01,4.804216e-01,4.758259e-01,NaN,NaN
1441,United States,USA,Fertilizer consumption (kilograms per hectare ...,AG.CON.FERT.ZS,NaN,41.334278,46.725537,51.064834,55.029481,61.038199,...,1.355551e+02,1.279752e+02,1.290263e+02,1.278152e+02,1.277166e+02,1.269114e+02,1.264800e+02,1.261560e+02,NaN,NaN

In [6]:
China_df2=China_df.dropna()
China_df2

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
13,China,CHN,Merchandise imports (current US$),TM.VAL.MRCH.CD.WT,2.648000e+09,1.747000e+09,1.373000e+09,1.450000e+09,1.710000e+09,2.246000e+09,...,1.818410e+12,1.949990e+12,1.959230e+12,1.679570e+12,1.587930e+12,1.843790e+12,2.135750e+12,2.078390e+12,2.065960e+12,2.687530e+12
25,China,CHN,Urban population,SP.URB.TOTL,1.080854e+08,1.103279e+08,1.146855e+08,1.211622e+08,1.277920e+08,1.293484e+08,...,7.009965e+08,7.226944e+08,7.443575e+08,7.658223e+08,7.873765e+08,8.092462e+08,8.297606e+08,8.489829e+08,8.668105e+08,8.828945e+08
26,China,CHN,Rural population,SP.RUR.TOTL,5.589846e+08,5.500021e+08,5.510845e+08,5.611728e+08,5.705630e+08,5.858366e+08,...,6.531935e+08,6.405456e+08,6.275025e+08,6.140377e+08,6.004135e+08,5.869688e+08,5.729994e+08,5.587621e+08,5.442895e+08,5.294655e+08
28,China,CHN,"Population, male",SP.POP.TOTL.MA.IN,3.438358e+08,3.401766e+08,3.428164e+08,3.511944e+08,3.592868e+08,3.677836e+08,...,6.958135e+08,7.003670e+08,7.046753e+08,7.086480e+08,7.125694e+08,7.167281e+08,7.199052e+08,7.222647e+08,7.237710e+08,7.241875e+08
30,China,CHN,"Age dependency ratio, old (% of working-age po...",SP.POP.DPND.OL,6.529573e+00,6.578584e+00,6.556231e+00,6.474128e+00,6.345924e+00,6.180308e+00,...,1.155186e+01,1.187585e+01,1.229971e+01,1.285122e+01,1.357653e+01,1.442482e+01,1.533786e+01,1.622124e+01,1.701975e+01,1.773531e+01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
953,China,CHN,"Population ages 15-19, female (% of female pop...",SP.POP.1519.FE.5Y,7.953896e+00,8.104841e+00,8.270831e+00,8.488618e+00,8.810683e+00,9.245859e+00,...,6.415332e+00,6.267354e+00,6.147142e+00,6.008871e+00,5.869958e+00,5.737016e+00,5.616052e+00,5.519569e+00,5.454289e+00,5.417855e+00
954,China,CHN,"Population ages 05-09, female (% of female pop...",SP.POP.0509.FE.5Y,1.468897e+01,1.489242e+01,1.460816e+01,1.391739e+01,1.309123e+01,1.246694e+01,...,5.686647e+00,5.677939e+00,5.684803e+00,5.695479e+00,5.709696e+00,5.728407e+00,5.747524e+00,5.761680e+00,5.764712e+00,5.758686e+00
955,China,CHN,"Population ages 0-14, male",SP.POP.0014.MA.IN,1.368991e+08,1.355996e+08,1.381004e+08,1.434190e+08,1.480174e+08,1.517310e+08,...,1.332889e+08,1.332763e+08,1.333557e+08,1.335277e+08,1.337780e+08,1.340880e+08,1.341774e+08,1.339910e+08,1.334571e+08,1.325346e+08
956,China,CHN,"Population ages 00-04, female (% of female pop...",SP.POP.0004.FE.5Y,1.474562e+01,1.395248e+01,1.395785e+01,1.449787e+01,1.514775e+01,1.564412e+01,...,5.935914e+00,5.940290e+00,5.933207e+00,5.918205e+00,5.902973e+00,5.860688e+00,5.797799e+00,5.720007e+00,5.630785e+00,5.517666e+00
1279,China,CHN,Population in largest city,EN.URB.LCTY,6.865312e+06,6.752117e+06,6.640636e+06,6.530995e+06,6.423017e+06,6.428131e+06,...,2.155545e+07,2.217887e+07,2.282123e+07,2.348218e+07,2.416323e+07,2.486208e+07,2.558214e+07,2.631710e+07,2.705848e+07,2.779570e+07

In [7]:
USA_df2 = USA_df.dropna()
USA_df2
# USA_df

Empty DataFrame
Columns: [Country Name, Country Code, Indicator Name, Indicator Code, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, Unnamed: 66]
Index: []

[0 rows x 67 columns]

In [8]:
display(China_df.iloc[448])

Country Name                  China
Country Code                    CHN
Indicator Name    GDP (current US$)
Indicator Code       NY.GDP.MKTP.CD
1960                    5.97165e+10
                        ...
2017                    1.23104e+13
2018                    1.38948e+13
2019                    1.42799e+13
2020                    1.46877e+13
2021                    1.77341e+13
Name: 448, Length: 66, dtype: object

In [9]:
display(China_df.iloc[451])

Country Name                                   China
Country Code                                     CHN
Indicator Name    Inflation, GDP deflator (annual %)
Indicator Code                     NY.GDP.DEFL.KD.ZG
1960                                             NaN
                                 ...
2017                                         4.23268
2018                                         3.49975
2019                                          1.2867
2020                                        0.491448
2021                                         4.37179
Name: 451, Length: 66, dtype: object

In [10]:
display(China_df.iloc[431])

Country Name                                                  China
Country Code                                                    CHN
Indicator Name    Unemployment, total (% of total labor force) (...
Indicator Code                                       SL.UEM.TOTL.ZS
1960                                                            NaN
                                        ...
2017                                                           4.44
2018                                                           4.28
2019                                                           4.52
2020                                                              5
2021                                                          4.817
Name: 431, Length: 66, dtype: object

In [11]:
display(China_df.iloc[708])

Country Name                   China
Country Code                     CHN
Indicator Name    CO2 emissions (kt)
Indicator Code        EN.ATM.CO2E.KT
1960                             NaN
                         ...
2017                      1.0096e+07
2018                     1.05029e+07
2019                     1.07072e+07
2020                             NaN
2021                             NaN
Name: 708, Length: 66, dtype: object

In [12]:
display(China_df.iloc[1218])

Country Name                                                 China
Country Code                                                   CHN
Indicator Name    Individuals using the Internet (% of population)
Indicator Code                                      IT.NET.USER.ZS
1960                                                           NaN
                                        ...
2017                                                          54.3
2018                                                          59.2
2019                                                       64.1098
2020                                                       70.4048
2021                                                           NaN
Name: 1218, Length: 66, dtype: object

In [13]:
display(China_df.iloc[532])

Country Name                                                  China
Country Code                                                    CHN
Indicator Name    Foreign direct investment, net inflows (% of GDP)
Indicator Code                                 BX.KLT.DINV.WD.GD.ZS
1960                                                            NaN
                                        ...
2017                                                        1.34913
2018                                                        1.69391
2019                                                        1.31072
2020                                                        1.72318
2021                                                            NaN
Name: 532, Length: 66, dtype: object

In [14]:
display(China_df.iloc[447])

Country Name                      China
Country Code                        CHN
Indicator Name    GDP growth (annual %)
Indicator Code        NY.GDP.MKTP.KD.ZG
1960                                NaN
                          ...
2017                             6.9472
2018                            6.74977
2019                             5.9505
2020                             2.2397
2021                            8.10979
Name: 447, Length: 66, dtype: object

In [15]:
China_list=['NY.GDP.MKTP.CD','NY.GDP.DEFL.KD.ZG','SP.POP.80UP.FE.5Y',
'SP.POP.7074.FE.5Y',
'SP.POP.65UP.MA.IN',
'SP.POP.6569.FE.5Y',
'SP.POP.5559.FE.5Y',
'SP.POP.4549.FE.5Y',
'SP.POP.3539.FE.5Y',
'SP.POP.2529.FE.5Y',
'SP.POP.1564.TO',
'SP.POP.1564.FE.IN',
'SP.POP.1014.FE.5Y',
'SP.POP.0014.TO',
'SP.POP.0014.FE.IN',
'HD.HCI.OVRL.UB', 'HD.HCI.OVRL.LB', 'NY.GDP.MKTP.CD', 'NY.GDP.MKTP.KD.ZG', 'SL.UEM.INTM.MA.ZS', 'SL.UEM.BASC.FE.ZS', 'SL.UEM.1524.ZS', 'SL.UEM.1524.FE.ZS', 'NY.GDP.DEFL.KD.ZG', 'EN.CO2.TRAN.ZS', 'EN.CO2.BLDG.ZS', 'EN.CO2.BLDG.ZS', 'BX.KLT.DINV.WD.GD.ZS'

]
data_china=China_df[China_df['Indicator Code'].isin(China_list)]
data_china

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
31,China,CHN,"Population ages 80 and above, female (% of fem...",SP.POP.80UP.FE.5Y,2.899782e-01,3.282729e-01,3.559775e-01,3.672127e-01,3.587298e-01,3.293456e-01,...,1.737560e+00,1.808777e+00,1.864808e+00,1.906224e+00,2.009170e+00,2.101204e+00,2.179912e+00,2.241569e+00,2.286628e+00,2.376489e+00
32,China,CHN,"Population ages 70-74, female (% of female pop...",SP.POP.7074.FE.5Y,1.305711e+00,1.310740e+00,1.309526e+00,1.299924e+00,1.279982e+00,1.250709e+00,...,2.399683e+00,2.411756e+00,2.454349e+00,2.536816e+00,2.631037e+00,2.748021e+00,2.898065e+00,3.098361e+00,3.355487e+00,3.637336e+00
33,China,CHN,"Population ages 65 and above, male",SP.POP.65UP.MA.IN,1.040649e+07,1.040332e+07,1.040070e+07,1.043423e+07,1.038643e+07,1.029888e+07,...,5.441672e+07,5.605056e+07,5.808124e+07,6.062870e+07,6.402532e+07,6.794624e+07,7.201218e+07,7.582671e+07,7.916296e+07,8.212616e+07
34,China,CHN,"Population ages 65-69, female (% of female pop...",SP.POP.6569.FE.5Y,2.076032e+00,2.039023e+00,1.975619e+00,1.909036e+00,1.866338e+00,1.857423e+00,...,3.177451e+00,3.340696e+00,3.556950e+00,3.831066e+00,4.137274e+00,4.510952e+00,4.892561e+00,5.193718e+00,5.366459e+00,5.395832e+00
35,China,CHN,"Population ages 55-59, female (% of female pop...",SP.POP.5559.FE.5Y,3.646981e+00,3.629279e+00,3.570017e+00,3.496774e+00,3.443943e+00,3.423601e+00,...,6.137570e+00,5.959107e+00,5.831226e+00,5.823525e+00,5.906365e+00,6.086935e+00,6.344220e+00,6.643041e+00,6.958221e+00,7.287862e+00
36,China,CHN,"Population ages 45-49, female (% of female pop...",SP.POP.4549.FE.5Y,4.932831e+00,4.947375e+00,4.928098e+00,4.883093e+00,4.823062e+00,4.750047e+00,...,8.259361e+00,8.603186e+00,8.870916e+00,9.026723e+00,9.076205e+00,9.025813e+00,8.881706e+00,8.657420e+00,8.367742e+00,8.021299e+00
37,China,CHN,"Population ages 35-39, female (% of female pop...",SP.POP.3539.FE.5Y,5.738536e+00,5.677073e+00,5.598823e+00,5.524227e+00,5.477104e+00,5.462105e+00,...,8.089537e+00,7.617409e+00,7.206976e+00,6.906939e+00,6.709267e+00,6.604155e+00,6.603480e+00,6.720571e+00,6.953015e+00,7.307881e+00
38,China,CHN,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,7.228109e+00,7.202961e+00,7.102287e+00,6.956615e+00,6.804426e+00,6.662224e+00,...,8.257108e+00,8.767980e+00,9.101253e+00,9.146155e+00,8.926822e+00,8.423282e+00,7.754962e+00,7.116008e+00,6.627831e+00,6.273891e+00
39,China,CHN,"Population ages 15-64, total",SP.POP.1564.TO,3.768232e+08,3.725206e+08,3.731189e+08,3.793327e+08,3.865285e+08,3.961968e+08,...,9.909560e+08,9.962685e+08,1.000076e+09,1.001976e+09,1.002023e+09,1.001331e+09,9.987948e+08,9.956037e+08,9.922843e+08,9.885306e+08
40,China,CHN,"Population ages 15-64, female",SP.POP.1564.FE.IN,1.802930e+08,1.783471e+08,1.788036e+08,1.819912e+08,1.856451e+08,1.904431e+08,...,4.828479e+08,4.852282e+08,4.868371e+08,4.874846e+08,4.872564e+08,4.866367e+08,4.850791e+08,4.831566e+08,4.811333e+08,4.790034e+08
41,China,CHN,"Population ages 10-14, female (% of female pop...",SP.POP.1014.FE.5Y,1.039497e+01,1.104324e+01,1.171476e+01,1.236041e+01,1.283838e+01,1.298577e+01,...,5.916269e+00,5.787864e+00,5.681943e+00,5.607396e+00,5.559472e+00,5.535063e+00,5.529169e+00,5.535715e+00,5.550440e+00,5.576303e+00
42,China,CHN,"Population ages 0-14, total",SP.POP.0014.TO,2.656419e+08,2.633028e+08,2.681886e+08,2.784438e+08,2.872977e+08,2.945020e+08,...,2.487601e+08,2.486562e+08,2.487781e+08,2.491177e+08,2.497275e+08,2.504441e+08,2.507714e+08,2.506421e+08,2.499314e+08,2.485104e+08
43,China,CHN,"Population ages 0-14, female",SP.POP.0014.FE.IN,1.287428e+08,1.277032e+08,1.300882e+08,1.350248e+08,1.392802e+08,1.427710e+08,...,1.154715e+08,1.153803e+08,1.154226e+08,1.155900e+08,1.159498e+08,1.163564e+08,1.165940e+08,1.166509e+08,1.164743e+08,1.159753e+08
447,China,CHN,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,-2.727000e+01,-5.580000e+00,1.030000e+01,1.818000e+01,1.695000e+01,...,7.863736e+00,7.766150e+00,7.425764e+00,7.041329e+00,6.848762e+00,6.947201e+00,6.749774e+00,5.950501e+00,2.239702e+00,8.109793e+00
448,China,CHN,GDP (current US$),NY.GDP.MKTP.CD,5.971647e+10,5.005687e+10,4.720936e+10,5.070680e+10,5.970834e+10,7.043627e+10,...,8.532230e+12,9.570410e+12,1.047570e+13,1.106160e+13,1.123330e+13,1.231040e+13,1.389480e+13,1.427990e+13,1.468770e+13,1.773410e+13
451,China,CHN,"Inflation, GDP deflator (annual %)",NY.GDP.DEFL.KD.ZG,NaN,1.525399e+01,-1.149649e-01,-2.621611e+00,-3.620385e-01,8.697808e-01,...,2.331218e+00,2.163370e+00,1.031064e+00,-2.944094e-03,1.407346e+00,4.232682e+00,3.499748e+00,1.286700e+00,4.914484e-01,4.371787e+00
532,China,CHN,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.827091e+00,3.039875e+00,2.559233e+00,2.192182e+00,1.555642e+00,1.349133e+00,1.693905e+00,1.310719e+00,1.723184e+00,NaN
698,China,CHN,CO2 emissions from transport (% of total fuel ...,EN.CO2.TRAN.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.099089e+00,8.386128e+00,8.598695e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
699,China,CHN,CO2 emissions from residential buildings and c...,EN.CO2.BLDG.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.302652e+00,5.306225e+00,5.358338e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
745,China,CHN,"Unemployment with intermediate education, male...",SL.UEM.INTM.MA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
746,China,CHN,"Unemployment with basic education, female (% o...",SL.UEM.BASC.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
747,China,CHN,"Unemployment, youth total (% of total labor fo...",SL.UEM.1524.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.013200e+01,1.032800e+01,1.051500e+01,1.068200e+01,1.054800e+01,1.041400e+01,1.009500e+01,1.071000e+01,1.193000e+01,1.135100e+01
748,China,CHN,"Unemployment, youth female (% of female labor ...",SL.UEM.1524.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.987000e+00,9.184000e+00,9.371000e+00,9.538000e+00,9.435000e+00,9.328000e+00,9.054000e+00,9.618000e+00,1.071300e+01,1.039900e+01
1049,China,CHN,"Human capital index (HCI), upper bound (scale ...",HD.HCI.OVRL.UB,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.830000e-01,6.589335e-01,NaN,6.652412e-01,NaN
1050,China,CHN,"Human capital index (HCI), lower bound (scale ...",HD.HCI.OVRL.LB,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.620000e-01,6.343280e-01,NaN,6.399794e-01,NaN

In [16]:
China_list=['NY.GDP.MKTP.CD','NY.GDP.DEFL.KD.ZG','SP.POP.80UP.FE.5Y',
'SP.POP.7074.FE.5Y',
'SP.POP.65UP.MA.IN',
'SP.POP.6569.FE.5Y',
'SP.POP.5559.FE.5Y',
'SP.POP.4549.FE.5Y',
'SP.POP.3539.FE.5Y',
'SP.POP.2529.FE.5Y',
'SP.POP.1564.TO',
'SP.POP.1564.FE.IN',
'SP.POP.1014.FE.5Y',
'SP.POP.0014.TO',
'SP.POP.0014.FE.IN',
'HD.HCI.OVRL.UB', 'HD.HCI.OVRL.LB', 'NY.GDP.MKTP.CD', 'NY.GDP.MKTP.KD.ZG', 'SL.UEM.INTM.MA.ZS', 'SL.UEM.BASC.FE.ZS', 'SL.UEM.1524.ZS', 'SL.UEM.1524.FE.ZS', 'NY.GDP.DEFL.KD.ZG', 'EN.CO2.TRAN.ZS', 'EN.CO2.BLDG.ZS', 'EN.CO2.BLDG.ZS', 'BX.KLT.DINV.WD.GD.ZS'

]
data_USA=USA_df[USA_df['Indicator Code'].isin(China_list)]
data_USA

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
31,United States,USA,"Population ages 80 and above, female (% of fem...",SP.POP.80UP.FE.5Y,1.661676e+00,1.749374e+00,1.828780e+00,1.894138e+00,1.941172e+00,1.971675e+00,...,4.583206e+00,4.573643e+00,4.565743e+00,4.603094e+00,4.627989e+00,4.649991e+00,4.679250e+00,4.724395e+00,4.810892e+00,NaN
32,United States,USA,"Population ages 70-74, female (% of female pop...",SP.POP.7074.FE.5Y,2.757785e+00,2.781829e+00,2.824388e+00,2.874921e+00,2.921573e+00,2.959758e+00,...,3.461234e+00,3.590331e+00,3.743772e+00,3.902046e+00,4.083038e+00,4.273034e+00,4.452723e+00,4.610393e+00,4.723517e+00,NaN
33,United States,USA,"Population ages 65 and above, male",SP.POP.65UP.MA.IN,7.339965e+06,7.483584e+06,7.604166e+06,7.711112e+06,7.814310e+06,7.907691e+06,...,1.929400e+07,2.002103e+07,2.076859e+07,2.155875e+07,2.232386e+07,2.306957e+07,2.381904e+07,2.472216e+07,2.541527e+07,NaN
34,United States,USA,"Population ages 65-69, female (% of female pop...",SP.POP.6569.FE.5Y,3.603942e+00,3.605321e+00,3.601358e+00,3.600412e+00,3.612164e+00,3.639238e+00,...,4.750702e+00,4.943363e+00,5.109233e+00,5.238113e+00,5.339715e+00,5.423872e+00,5.506100e+00,5.593793e+00,5.667037e+00,NaN
35,United States,USA,"Population ages 55-59, female (% of female pop...",SP.POP.5559.FE.5Y,5.117633e+00,5.103825e+00,5.098101e+00,5.110025e+00,5.135565e+00,5.159778e+00,...,6.686838e+00,6.738563e+00,6.759288e+00,6.750586e+00,6.715929e+00,6.657678e+00,6.579049e+00,6.482731e+00,6.364062e+00,NaN
36,United States,USA,"Population ages 45-49, female (% of female pop...",SP.POP.4549.FE.5Y,6.050475e+00,5.992454e+00,5.939841e+00,5.903686e+00,5.889605e+00,5.894766e+00,...,6.672118e+00,6.519009e+00,6.388692e+00,6.281912e+00,6.198330e+00,6.133775e+00,6.079804e+00,6.030919e+00,5.985030e+00,NaN
37,United States,USA,"Population ages 35-39, female (% of female pop...",SP.POP.3539.FE.5Y,6.863100e+00,6.758135e+00,6.627906e+00,6.476120e+00,6.309646e+00,6.135857e+00,...,6.251508e+00,6.231513e+00,6.232015e+00,6.249279e+00,6.282104e+00,6.327042e+00,6.378706e+00,6.432925e+00,6.482960e+00,NaN
38,United States,USA,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,5.998961e+00,5.869454e+00,5.787910e+00,5.750699e+00,5.754819e+00,5.802015e+00,...,6.718594e+00,6.771193e+00,6.826615e+00,6.877950e+00,6.931843e+00,6.978185e+00,7.001259e+00,6.991455e+00,6.940717e+00,NaN
39,United States,USA,"Population ages 15-64, total",SP.POP.1564.TO,1.087516e+08,1.102269e+08,1.119057e+08,1.137320e+08,1.156485e+08,1.174982e+08,...,2.101100e+08,2.111413e+08,2.121156e+08,2.130431e+08,2.136771e+08,2.140245e+08,2.142060e+08,2.154668e+08,2.147971e+08,NaN
40,United States,USA,"Population ages 15-64, female",SP.POP.1564.FE.IN,5.489091e+07,5.562528e+07,5.644738e+07,5.733461e+07,5.826694e+07,5.917083e+07,...,1.048579e+08,1.053244e+08,1.057612e+08,1.061936e+08,1.064823e+08,1.066284e+08,1.066889e+08,1.072821e+08,1.069302e+08,NaN
41,United States,USA,"Population ages 10-14, female (% of female pop...",SP.POP.1014.FE.5Y,8.970117e+00,9.118514e+00,9.219836e+00,9.287382e+00,9.344493e+00,9.409482e+00,...,6.348837e+00,6.299850e+00,6.254296e+00,6.252288e+00,6.250954e+00,6.244904e+00,6.220968e+00,6.166835e+00,6.114590e+00,NaN
42,United States,USA,"Population ages 0-14, total",SP.POP.0014.TO,5.544988e+07,5.658158e+07,5.736512e+07,5.787088e+07,5.822474e+07,5.842286e+07,...,6.200163e+07,6.181866e+07,6.165799e+07,6.145905e+07,6.131325e+07,6.114829e+07,6.090296e+07,6.090254e+07,6.055075e+07,NaN
43,United States,USA,"Population ages 0-14, female",SP.POP.0014.FE.IN,2.713724e+07,2.769030e+07,2.806997e+07,2.831338e+07,2.848391e+07,2.857998e+07,...,3.030715e+07,3.021656e+07,3.013775e+07,3.004155e+07,2.997247e+07,2.989450e+07,2.977648e+07,2.977677e+07,2.960846e+07,NaN
732,United States,USA,"Unemployment with intermediate education, male...",SL.UEM.INTM.MA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.006000e+01,8.220000e+00,7.160000e+00,6.520000e+00,5.790000e+00,5.160000e+00,4.850000e+00,9.970000e+00,7.090000e+00,NaN
733,United States,USA,"Unemployment with basic education, female (% o...",SL.UEM.BASC.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.308000e+01,1.155000e+01,8.990000e+00,9.690000e+00,8.020000e+00,7.080000e+00,6.850000e+00,1.399000e+01,9.760000e+00,NaN
734,United States,USA,"Unemployment, youth total (% of total labor fo...",SL.UEM.1524.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.547100e+01,1.334300e+01,1.155500e+01,1.036100e+01,9.201000e+00,8.576000e+00,8.340000e+00,1.485100e+01,9.574000e+00,NaN
735,United States,USA,"Unemployment, youth female (% of female labor ...",SL.UEM.1524.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.384600e+01,1.211300e+01,1.033200e+01,9.274000e+00,8.052000e+00,7.632000e+00,7.295000e+00,1.477500e+01,8.571000e+00,NaN
884,United States,USA,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.710668e+00,1.435021e+00,2.809148e+00,2.537498e+00,1.954982e+00,1.046005e+00,1.472654e+00,7.127109e-01,NaN,NaN
1024,United States,USA,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,2.300000e+00,6.100000e+00,4.400000e+00,5.800000e+00,6.400000e+00,...,1.841875e+00,2.287776e+00,2.706370e+00,1.667472e+00,2.255680e+00,2.918857e+00,2.288870e+00,-3.404590e+00,5.671107e+00,NaN
1025,United States,USA,GDP (current US$),NY.GDP.MKTP.CD,5.433000e+11,5.633000e+11,6.051000e+11,6.386000e+11,6.858000e+11,7.437000e+11,...,1.684319e+13,1.755068e+13,1.820602e+13,1.869511e+13,1.947962e+13,2.052716e+13,2.137257e+13,2.089374e+13,2.299610e+13,NaN
1028,United States,USA,"Inflation, GDP deflator (annual %)",NY.GDP.DEFL.KD.ZG,NaN,1.350154e+00,1.244635e+00,1.088386e+00,1.503940e+00,1.919826e+00,...,1.750950e+00,1.869891e+00,1.000542e+00,1.002235e+00,1.897844e+00,2.389011e+00,1.788716e+00,1.205235e+00,4.155370e+00,NaN
1168,United States,USA,"Human capital index (HCI), upper bound (scale ...",HD.HCI.OVRL.UB,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7.730000e-01,7.221820e-01,NaN,7.108814e-01,NaN,NaN
1169,United States,USA,"Human capital index (HCI), lower bound (scale ...",HD.HCI.OVRL.LB,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7.510000e-01,7.051016e-01,NaN,6.925232e-01,NaN,NaN
1395,United States,USA,CO2 emissions from transport (% of total fuel ...,EN.CO2.TRAN.ZS,2.373140e+01,2.410399e+01,2.420425e+01,2.408145e+01,2.415595e+01,2.356003e+01,...,3.308297e+01,3.339799e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1396,United States,USA,CO2 emissions from residential buildings and c...,EN.CO2.BLDG.ZS,1.954037e+01,1.980406e+01,1.996034e+01,1.900930e+01,1.833901e+01,1.813371e+01,...,1.067944e+01,1.101192e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
# data=data_china.drop(data_china['1960', '1961'], axis=1)
# data=data_china.drop(columns=['1960', '1990'])
# data
china_data=data_china.drop(data_china.iloc[:, 4:31], inplace=False, axis=1)
china_data

,Country Name,Country Code,Indicator Name,Indicator Code,1987,1988,1989,1990,1991,1992,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
31,China,CHN,"Population ages 80 and above, female (% of fem...",SP.POP.80UP.FE.5Y,7.891007e-01,8.125245e-01,8.281091e-01,8.382873e-01,8.926771e-01,9.424621e-01,...,1.737560e+00,1.808777e+00,1.864808e+00,1.906224e+00,2.009170e+00,2.101204e+00,2.179912e+00,2.241569e+00,2.286628e+00,2.376489e+00
32,China,CHN,"Population ages 70-74, female (% of female pop...",SP.POP.7074.FE.5Y,1.795825e+00,1.814956e+00,1.832681e+00,1.848750e+00,1.834212e+00,1.825701e+00,...,2.399683e+00,2.411756e+00,2.454349e+00,2.536816e+00,2.631037e+00,2.748021e+00,2.898065e+00,3.098361e+00,3.355487e+00,3.637336e+00
33,China,CHN,"Population ages 65 and above, male",SP.POP.65UP.MA.IN,2.725961e+07,2.804623e+07,2.886631e+07,2.979341e+07,3.064278e+07,3.163042e+07,...,5.441672e+07,5.605056e+07,5.808124e+07,6.062870e+07,6.402532e+07,6.794624e+07,7.201218e+07,7.582671e+07,7.916296e+07,8.212616e+07
34,China,CHN,"Population ages 65-69, female (% of female pop...",SP.POP.6569.FE.5Y,2.342521e+00,2.311565e+00,2.293391e+00,2.295068e+00,2.282511e+00,2.294760e+00,...,3.177451e+00,3.340696e+00,3.556950e+00,3.831066e+00,4.137274e+00,4.510952e+00,4.892561e+00,5.193718e+00,5.366459e+00,5.395832e+00
35,China,CHN,"Population ages 55-59, female (% of female pop...",SP.POP.5559.FE.5Y,3.331959e+00,3.382893e+00,3.427307e+00,3.460406e+00,3.457660e+00,3.464865e+00,...,6.137570e+00,5.959107e+00,5.831226e+00,5.823525e+00,5.906365e+00,6.086935e+00,6.344220e+00,6.643041e+00,6.958221e+00,7.287862e+00
36,China,CHN,"Population ages 45-49, female (% of female pop...",SP.POP.4549.FE.5Y,4.079657e+00,4.026021e+00,4.015778e+00,4.066817e+00,4.148581e+00,4.290831e+00,...,8.259361e+00,8.603186e+00,8.870916e+00,9.026723e+00,9.076205e+00,9.025813e+00,8.881706e+00,8.657420e+00,8.367742e+00,8.021299e+00
37,China,CHN,"Population ages 35-39, female (% of female pop...",SP.POP.3539.FE.5Y,6.796496e+00,7.229179e+00,7.541668e+00,7.681838e+00,7.635138e+00,7.457896e+00,...,8.089537e+00,7.617409e+00,7.206976e+00,6.906939e+00,6.709267e+00,6.604155e+00,6.603480e+00,6.720571e+00,6.953015e+00,7.307881e+00
38,China,CHN,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,8.269648e+00,8.485342e+00,8.757146e+00,9.058589e+00,9.354057e+00,9.726185e+00,...,8.257108e+00,8.767980e+00,9.101253e+00,9.146155e+00,8.926822e+00,8.423282e+00,7.754962e+00,7.116008e+00,6.627831e+00,6.273891e+00
39,China,CHN,"Population ages 15-64, total",SP.POP.1564.TO,7.033897e+08,7.183101e+08,7.325311e+08,7.467261e+08,7.566776e+08,7.689524e+08,...,9.909560e+08,9.962685e+08,1.000076e+09,1.001976e+09,1.002023e+09,1.001331e+09,9.987948e+08,9.956037e+08,9.922843e+08,9.885306e+08
40,China,CHN,"Population ages 15-64, female",SP.POP.1564.FE.IN,3.402257e+08,3.475454e+08,3.545458e+08,3.615797e+08,3.666204e+08,3.728160e+08,...,4.828479e+08,4.852282e+08,4.868371e+08,4.874846e+08,4.872564e+08,4.866367e+08,4.850791e+08,4.831566e+08,4.811333e+08,4.790034e+08
41,China,CHN,"Population ages 10-14, female (% of female pop...",SP.POP.1014.FE.5Y,1.029240e+01,9.568463e+00,8.932364e+00,8.468334e+00,8.138435e+00,7.989395e+00,...,5.916269e+00,5.787864e+00,5.681943e+00,5.607396e+00,5.559472e+00,5.535063e+00,5.529169e+00,5.535715e+00,5.550440e+00,5.576303e+00
42,China,CHN,"Population ages 0-14, total",SP.POP.0014.TO,3.215475e+08,3.227144e+08,3.239551e+08,3.245462e+08,3.285817e+08,3.285968e+08,...,2.487601e+08,2.486562e+08,2.487781e+08,2.491177e+08,2.497275e+08,2.504441e+08,2.507714e+08,2.506421e+08,2.499314e+08,2.485104e+08
43,China,CHN,"Population ages 0-14, female",SP.POP.0014.FE.IN,1.557954e+08,1.563045e+08,1.568365e+08,1.570221e+08,1.588147e+08,1.586188e+08,...,1.154715e+08,1.153803e+08,1.154226e+08,1.155900e+08,1.159498e+08,1.163564e+08,1.165940e+08,1.166509e+08,1.164743e+08,1.159753e+08
447,China,CHN,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,1.165743e+01,1.122259e+01,4.206334e+00,3.920251e+00,9.262786e+00,1.422453e+01,...,7.863736e+00,7.766150e+00,7.425764e+00,7.041329e+00,6.848762e+00,6.947201e+00,6.749774e+00,5.950501e+00,2.239702e+00,8.109793e+00
448,China,CHN,GDP (current US$),NY.GDP.MKTP.CD,2.729730e+11,3.123540e+11,3.477680e+11,3.608580e+11,3.833730e+11,4.269160e+11,...,8.532230e+12,9.570410e+12,1.047570e+13,1.106160e+13,1.123330e+13,1.231040e+13,1.389480e+13,1.427990e+13,1.468770e+13,1.773410e+13
451,China,CHN,"Inflation, GDP deflator (annual %)",NY.GDP.DEFL.KD.ZG,5.082516e+00,1.210766e+01,8.602465e+00,5.711224e+00,6.714537e+00,8.190323e+00,...,2.331218e+00,2.163370e+00,1.031064e+00,-2.944094e-03,1.407346e+00,4.232682e+00,3.499748e+00,1.286700e+00,4.914484e-01,4.371787e+00
532,China,CHN,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,8.477030e-01,1.022559e+00,9.756503e-01,9.663083e-01,1.138838e+00,2.613162e+00,...,2.827091e+00,3.039875e+00,2.559233e+00,2.192182e+00,1.555642e+00,1.349133e+00,1.693905e+00,1.310719e+00,1.723184e+00,NaN
698,China,CHN,CO2 emissions from transport (% of total fuel ...,EN.CO2.TRAN.ZS,6.072014e+00,5.970777e+00,5.989969e+00,5.155737e+00,5.226893e+00,5.491394e+00,...,8.099089e+00,8.386128e+00,8.598695e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
699,China,CHN,CO2 emissions from residential buildings and c...,EN.CO2.BLDG.ZS,1.892252e+01,1.886040e+01,1.805268e+01,1.791189e+01,1.689870e+01,1.516017e+01,...,5.302652e+00,5.306225e+00,5.358338e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
745,China,CHN,"Unemployment with intermediate education, male...",SL.UEM.INTM.MA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
746,China,CHN,"Unemployment with basic education, female (% o...",SL.UEM.BASC.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
747,China,CHN,"Unemployment, youth total (% of total labor fo...",SL.UEM.1524.ZS,NaN,NaN,NaN,NaN,4.365000e+00,4.436000e+00,...,1.013200e+01,1.032800e+01,1.051500e+01,1.068200e+01,1.054800e+01,1.041400e+01,1.009500e+01,1.071000e+01,1.193000e+01,1.135100e+01
748,China,CHN,"Unemployment, youth female (% of female labor ...",SL.UEM.1524.FE.ZS,NaN,NaN,NaN,NaN,3.763000e+00,3.832000e+00,...,8.987000e+00,9.184000e+00,9.371000e+00,9.538000e+00,9.435000e+00,9.328000e+00,9.054000e+00,9.618000e+00,1.071300e+01,1.039900e+01
1049,China,CHN,"Human capital index (HCI), upper bound (scale ...",HD.HCI.OVRL.UB,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.830000e-01,6.589335e-01,NaN,6.652412e-01,NaN
1050,China,CHN,"Human capital index (HCI), lower bound (scale ...",HD.HCI.OVRL.LB,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.620000e-01,6.343280e-01,NaN,6.399794e-01,NaN

In [18]:
USA_data=data_USA.drop(data_USA.iloc[:, 4:34], inplace=False, axis=1)
USA_data

,Country Name,Country Code,Indicator Name,Indicator Code,1990,1991,1992,1993,1994,1995,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
31,United States,USA,"Population ages 80 and above, female (% of fem...",SP.POP.80UP.FE.5Y,3.886848e+00,3.976265e+00,4.036392e+00,4.070733e+00,4.086466e+00,4.092333e+00,...,4.583206e+00,4.573643e+00,4.565743e+00,4.603094e+00,4.627989e+00,4.649991e+00,4.679250e+00,4.724395e+00,4.810892e+00,NaN
32,United States,USA,"Population ages 70-74, female (% of female pop...",SP.POP.7074.FE.5Y,3.610857e+00,3.629779e+00,3.657391e+00,3.678209e+00,3.682393e+00,3.671750e+00,...,3.461234e+00,3.590331e+00,3.743772e+00,3.902046e+00,4.083038e+00,4.273034e+00,4.452723e+00,4.610393e+00,4.723517e+00,NaN
33,United States,USA,"Population ages 65 and above, male",SP.POP.65UP.MA.IN,1.278873e+07,1.303860e+07,1.327638e+07,1.348643e+07,1.366035e+07,1.380253e+07,...,1.929400e+07,2.002103e+07,2.076859e+07,2.155875e+07,2.232386e+07,2.306957e+07,2.381904e+07,2.472216e+07,2.541527e+07,NaN
34,United States,USA,"Population ages 65-69, female (% of female pop...",SP.POP.6569.FE.5Y,4.319346e+00,4.263939e+00,4.198566e+00,4.130739e+00,4.062679e+00,3.991325e+00,...,4.750702e+00,4.943363e+00,5.109233e+00,5.238113e+00,5.339715e+00,5.423872e+00,5.506100e+00,5.593793e+00,5.667037e+00,NaN
35,United States,USA,"Population ages 55-59, female (% of female pop...",SP.POP.5559.FE.5Y,4.261091e+00,4.203159e+00,4.175039e+00,4.175211e+00,4.202257e+00,4.256622e+00,...,6.686838e+00,6.738563e+00,6.759288e+00,6.750586e+00,6.715929e+00,6.657678e+00,6.579049e+00,6.482731e+00,6.364062e+00,NaN
36,United States,USA,"Population ages 45-49, female (% of female pop...",SP.POP.4549.FE.5Y,5.511357e+00,5.728938e+00,5.965495e+00,6.196125e+00,6.397533e+00,6.564136e+00,...,6.672118e+00,6.519009e+00,6.388692e+00,6.281912e+00,6.198330e+00,6.133775e+00,6.079804e+00,6.030919e+00,5.985030e+00,NaN
37,United States,USA,"Population ages 35-39, female (% of female pop...",SP.POP.3539.FE.5Y,7.892724e+00,7.984140e+00,8.084100e+00,8.171072e+00,8.223906e+00,8.238074e+00,...,6.251508e+00,6.231513e+00,6.232015e+00,6.249279e+00,6.282104e+00,6.327042e+00,6.378706e+00,6.432925e+00,6.482960e+00,NaN
38,United States,USA,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,8.142566e+00,7.973726e+00,7.784458e+00,7.574339e+00,7.357940e+00,7.153119e+00,...,6.718594e+00,6.771193e+00,6.826615e+00,6.877950e+00,6.931843e+00,6.978185e+00,7.001259e+00,6.991455e+00,6.940717e+00,NaN
39,United States,USA,"Population ages 15-64, total",SP.POP.1564.TO,1.639966e+08,1.657746e+08,1.677466e+08,1.697485e+08,1.717770e+08,1.739387e+08,...,2.101100e+08,2.111413e+08,2.121156e+08,2.130431e+08,2.136771e+08,2.140245e+08,2.142060e+08,2.154668e+08,2.147971e+08,NaN
40,United States,USA,"Population ages 15-64, female",SP.POP.1564.FE.IN,8.214064e+07,8.301830e+07,8.397429e+07,8.492640e+07,8.588136e+07,8.690202e+07,...,1.048579e+08,1.053244e+08,1.057612e+08,1.061936e+08,1.064823e+08,1.066284e+08,1.066889e+08,1.072821e+08,1.069302e+08,NaN
41,United States,USA,"Population ages 10-14, female (% of female pop...",SP.POP.1014.FE.5Y,6.604138e+00,6.622758e+00,6.663403e+00,6.718742e+00,6.779507e+00,6.836298e+00,...,6.348837e+00,6.299850e+00,6.254296e+00,6.252288e+00,6.250954e+00,6.244904e+00,6.220968e+00,6.166835e+00,6.114590e+00,NaN
42,United States,USA,"Population ages 0-14, total",SP.POP.0014.TO,5.410453e+07,5.515057e+07,5.620244e+07,5.715418e+07,5.795283e+07,5.862180e+07,...,6.200163e+07,6.181866e+07,6.165799e+07,6.145905e+07,6.131325e+07,6.114829e+07,6.090296e+07,6.090254e+07,6.055075e+07,NaN
43,United States,USA,"Population ages 0-14, female",SP.POP.0014.FE.IN,2.642366e+07,2.693980e+07,2.745450e+07,2.791992e+07,2.831008e+07,2.863488e+07,...,3.030715e+07,3.021656e+07,3.013775e+07,3.004155e+07,2.997247e+07,2.989450e+07,2.977648e+07,2.977677e+07,2.960846e+07,NaN
732,United States,USA,"Unemployment with intermediate education, male...",SL.UEM.INTM.MA.ZS,NaN,NaN,NaN,NaN,7.320000e+00,6.620000e+00,...,1.006000e+01,8.220000e+00,7.160000e+00,6.520000e+00,5.790000e+00,5.160000e+00,4.850000e+00,9.970000e+00,7.090000e+00,NaN
733,United States,USA,"Unemployment with basic education, female (% o...",SL.UEM.BASC.FE.ZS,NaN,NaN,NaN,NaN,1.435000e+01,1.375000e+01,...,1.308000e+01,1.155000e+01,8.990000e+00,9.690000e+00,8.020000e+00,7.080000e+00,6.850000e+00,1.399000e+01,9.760000e+00,NaN
734,United States,USA,"Unemployment, youth total (% of total labor fo...",SL.UEM.1524.ZS,NaN,1.345900e+01,1.428000e+01,1.341700e+01,1.255700e+01,1.219300e+01,...,1.547100e+01,1.334300e+01,1.155500e+01,1.036100e+01,9.201000e+00,8.576000e+00,8.340000e+00,1.485100e+01,9.574000e+00,NaN
735,United States,USA,"Unemployment, youth female (% of female labor ...",SL.UEM.1524.FE.ZS,NaN,1.244700e+01,1.301400e+01,1.236200e+01,1.183500e+01,1.180200e+01,...,1.384600e+01,1.211300e+01,1.033200e+01,9.274000e+00,8.052000e+00,7.632000e+00,7.295000e+00,1.477500e+01,8.571000e+00,NaN
884,United States,USA,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,1.194504e+00,5.610470e-01,4.648540e-01,7.323696e-01,7.676436e-01,9.042182e-01,...,1.710668e+00,1.435021e+00,2.809148e+00,2.537498e+00,1.954982e+00,1.046005e+00,1.472654e+00,7.127109e-01,NaN,NaN
1024,United States,USA,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,1.885965e+00,-1.082648e-01,3.522441e+00,2.751781e+00,4.028793e+00,2.684217e+00,...,1.841875e+00,2.287776e+00,2.706370e+00,1.667472e+00,2.255680e+00,2.918857e+00,2.288870e+00,-3.404590e+00,5.671107e+00,NaN
1025,United States,USA,GDP (current US$),NY.GDP.MKTP.CD,5.963144e+12,6.158129e+12,6.520327e+12,6.858559e+12,7.287236e+12,7.639749e+12,...,1.684319e+13,1.755068e+13,1.820602e+13,1.869511e+13,1.947962e+13,2.052716e+13,2.137257e+13,2.089374e+13,2.299610e+13,NaN
1028,United States,USA,"Inflation, GDP deflator (annual %)",NY.GDP.DEFL.KD.ZG,3.743330e+00,3.381762e+00,2.278910e+00,2.370340e+00,2.135424e+00,2.096901e+00,...,1.750950e+00,1.869891e+00,1.000542e+00,1.002235e+00,1.897844e+00,2.389011e+00,1.788716e+00,1.205235e+00,4.155370e+00,NaN
1168,United States,USA,"Human capital index (HCI), upper bound (scale ...",HD.HCI.OVRL.UB,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7.730000e-01,7.221820e-01,NaN,7.108814e-01,NaN,NaN
1169,United States,USA,"Human capital index (HCI), lower bound (scale ...",HD.HCI.OVRL.LB,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7.510000e-01,7.051016e-01,NaN,6.925232e-01,NaN,NaN
1395,United States,USA,CO2 emissions from transport (% of total fuel ...,EN.CO2.TRAN.ZS,2.971108e+01,2.937074e+01,2.957454e+01,2.936267e+01,2.999470e+01,3.030860e+01,...,3.308297e+01,3.339799e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1396,United States,USA,CO2 emissions from residential buildings and c...,EN.CO2.BLDG.ZS,1.135462e+01,1.164748e+01,1.167849e+01,1.182132e+01,1.145992e+01,1.143011e+01,...,1.067944e+01,1.101192e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
USA_data=USA_data.drop(columns=['Unnamed: 66'])
USA_data

,Country Name,Country Code,Indicator Name,Indicator Code,1990,1991,1992,1993,1994,1995,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
31,United States,USA,"Population ages 80 and above, female (% of fem...",SP.POP.80UP.FE.5Y,3.886848e+00,3.976265e+00,4.036392e+00,4.070733e+00,4.086466e+00,4.092333e+00,...,4.586069e+00,4.583206e+00,4.573643e+00,4.565743e+00,4.603094e+00,4.627989e+00,4.649991e+00,4.679250e+00,4.724395e+00,4.810892e+00
32,United States,USA,"Population ages 70-74, female (% of female pop...",SP.POP.7074.FE.5Y,3.610857e+00,3.629779e+00,3.657391e+00,3.678209e+00,3.682393e+00,3.671750e+00,...,3.355915e+00,3.461234e+00,3.590331e+00,3.743772e+00,3.902046e+00,4.083038e+00,4.273034e+00,4.452723e+00,4.610393e+00,4.723517e+00
33,United States,USA,"Population ages 65 and above, male",SP.POP.65UP.MA.IN,1.278873e+07,1.303860e+07,1.327638e+07,1.348643e+07,1.366035e+07,1.380253e+07,...,1.860625e+07,1.929400e+07,2.002103e+07,2.076859e+07,2.155875e+07,2.232386e+07,2.306957e+07,2.381904e+07,2.472216e+07,2.541527e+07
34,United States,USA,"Population ages 65-69, female (% of female pop...",SP.POP.6569.FE.5Y,4.319346e+00,4.263939e+00,4.198566e+00,4.130739e+00,4.062679e+00,3.991325e+00,...,4.545043e+00,4.750702e+00,4.943363e+00,5.109233e+00,5.238113e+00,5.339715e+00,5.423872e+00,5.506100e+00,5.593793e+00,5.667037e+00
35,United States,USA,"Population ages 55-59, female (% of female pop...",SP.POP.5559.FE.5Y,4.261091e+00,4.203159e+00,4.175039e+00,4.175211e+00,4.202257e+00,4.256622e+00,...,6.612851e+00,6.686838e+00,6.738563e+00,6.759288e+00,6.750586e+00,6.715929e+00,6.657678e+00,6.579049e+00,6.482731e+00,6.364062e+00
36,United States,USA,"Population ages 45-49, female (% of female pop...",SP.POP.4549.FE.5Y,5.511357e+00,5.728938e+00,5.965495e+00,6.196125e+00,6.397533e+00,6.564136e+00,...,6.837456e+00,6.672118e+00,6.519009e+00,6.388692e+00,6.281912e+00,6.198330e+00,6.133775e+00,6.079804e+00,6.030919e+00,5.985030e+00
37,United States,USA,"Population ages 35-39, female (% of female pop...",SP.POP.3539.FE.5Y,7.892724e+00,7.984140e+00,8.084100e+00,8.171072e+00,8.223906e+00,8.238074e+00,...,6.289322e+00,6.251508e+00,6.231513e+00,6.232015e+00,6.249279e+00,6.282104e+00,6.327042e+00,6.378706e+00,6.432925e+00,6.482960e+00
38,United States,USA,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,8.142566e+00,7.973726e+00,7.784458e+00,7.574339e+00,7.357940e+00,7.153119e+00,...,6.669776e+00,6.718594e+00,6.771193e+00,6.826615e+00,6.877950e+00,6.931843e+00,6.978185e+00,7.001259e+00,6.991455e+00,6.940717e+00
39,United States,USA,"Population ages 15-64, total",SP.POP.1564.TO,1.639966e+08,1.657746e+08,1.677466e+08,1.697485e+08,1.717770e+08,1.739387e+08,...,2.090909e+08,2.101100e+08,2.111413e+08,2.121156e+08,2.130431e+08,2.136771e+08,2.140245e+08,2.142060e+08,2.154668e+08,2.147971e+08
40,United States,USA,"Population ages 15-64, female",SP.POP.1564.FE.IN,8.214064e+07,8.301830e+07,8.397429e+07,8.492640e+07,8.588136e+07,8.690202e+07,...,1.043952e+08,1.048579e+08,1.053244e+08,1.057612e+08,1.061936e+08,1.064823e+08,1.066284e+08,1.066889e+08,1.072821e+08,1.069302e+08
41,United States,USA,"Population ages 10-14, female (% of female pop...",SP.POP.1014.FE.5Y,6.604138e+00,6.622758e+00,6.663403e+00,6.718742e+00,6.779507e+00,6.836298e+00,...,6.399160e+00,6.348837e+00,6.299850e+00,6.254296e+00,6.252288e+00,6.250954e+00,6.244904e+00,6.220968e+00,6.166835e+00,6.114590e+00
42,United States,USA,"Population ages 0-14, total",SP.POP.0014.TO,5.410453e+07,5.515057e+07,5.620244e+07,5.715418e+07,5.795283e+07,5.862180e+07,...,6.222050e+07,6.200163e+07,6.181866e+07,6.165799e+07,6.145905e+07,6.131325e+07,6.114829e+07,6.090296e+07,6.090254e+07,6.055075e+07
43,United States,USA,"Population ages 0-14, female",SP.POP.0014.FE.IN,2.642366e+07,2.693980e+07,2.745450e+07,2.791992e+07,2.831008e+07,2.863488e+07,...,3.041395e+07,3.030715e+07,3.021656e+07,3.013775e+07,3.004155e+07,2.997247e+07,2.989450e+07,2.977648e+07,2.977677e+07,2.960846e+07
732,United States,USA,"Unemployment with intermediate education, male...",SL.UEM.INTM.MA.ZS,NaN,NaN,NaN,NaN,7.320000e+00,6.620000e+00,...,1.065000e+01,1.006000e+01,8.220000e+00,7.160000e+00,6.520000e+00,5.790000e+00,5.160000e+00,4.850000e+00,9.970000e+00,7.090000e+00
733,United States,USA,"Unemployment with basic education, female (% o...",SL.UEM.BASC.FE.ZS,NaN,NaN,NaN,NaN,1.435000e+01,1.375000e+01,...,1.483000e+01,1.308000e+01,1.155000e+01,8.990000e+00,9.690000e+00,8.020000e+00,7.080000e+00,6.850000e+00,1.399000e+01,9.760000e+00
734,United States,USA,"Unemployment, youth total (% of total labor fo...",SL.UEM.1524.ZS,NaN,1.345900e+01,1.428000e+01,1.341700e+01,1.255700e+01,1.219300e+01,...,1.615200e+01,1.547100e+01,1.334300e+01,1.155500e+01,1.036100e+01,9.201000e+00,8.576000e+00,8.340000e+00,1.485100e+01,9.574000e+00
735,United States,USA,"Unemployment, youth female (% of female labor ...",SL.UEM.1524.FE.ZS,NaN,1.244700e+01,1.301400e+01,1.236200e+01,1.183500e+01,1.180200e+01,...,1.458800e+01,1.384600e+01,1.211300e+01,1.033200e+01,9.274000e+00,8.052000e+00,7.632000e+00,7.295000e+00,1.477500e+01,8.571000e+00
884,United States,USA,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,1.194504e+00,5.610470e-01,4.648540e-01,7.323696e-01,7.676436e-01,9.042182e-01,...,1.540208e+00,1.710668e+00,1.435021e+00,2.809148e+00,2.537498e+00,1.954982e+00,1.046005e+00,1.472654e+00,7.127109e-01,NaN
1024,United States,USA,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,1.885965e+00,-1.082648e-01,3.522441e+00,2.751781e+00,4.028793e+00,2.684217e+00,...,2.280688e+00,1.841875e+00,2.287776e+00,2.706370e+00,1.667472e+00,2.255680e+00,2.918857e+00,2.288870e+00,-3.404590e+00,5.671107e+00
1025,United States,USA,GDP (current US$),NY.GDP.MKTP.CD,5.963144e+12,6.158129e+12,6.520327e+12,6.858559e+12,7.287236e+12,7.639749e+12,...,1.625397e+13,1.684319e+13,1.755068e+13,1.820602e+13,1.869511e+13,1.947962e+13,2.052716e+13,2.137257e+13,2.089374e+13,2.299610e+13
1028,United States,USA,"Inflation, GDP deflator (annual %)",NY.GDP.DEFL.KD.ZG,3.743330e+00,3.381762e+00,2.278910e+00,2.370340e+00,2.135424e+00,2.096901e+00,...,1.870596e+00,1.750950e+00,1.869891e+00,1.000542e+00,1.002235e+00,1.897844e+00,2.389011e+00,1.788716e+00,1.205235e+00,4.155370e+00
1168,United States,USA,"Human capital index (HCI), upper bound (scale ...",HD.HCI.OVRL.UB,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,7.730000e-01,7.221820e-01,NaN,7.108814e-01,NaN
1169,United States,USA,"Human capital index (HCI), lower bound (scale ...",HD.HCI.OVRL.LB,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,7.510000e-01,7.051016e-01,NaN,6.925232e-01,NaN
1395,United States,USA,CO2 emissions from transport (% of total fuel ...,EN.CO2.TRAN.ZS,2.971108e+01,2.937074e+01,2.957454e+01,2.936267e+01,2.999470e+01,3.030860e+01,...,3.362544e+01,3.308297e+01,3.339799e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1396,United States,USA,CO2 emissions from residential buildings and c...,EN.CO2.BLDG.ZS,1.135462e+01,1.164748e+01,1.167849e+01,1.182132e+01,1.145992e+01,1.143011e+01,...,9.712099e+00,1.067944e+01,1.101192e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
protocol = 'postgresql'
username = 'postgres'
password = 'postgres'
host = 'localhost'
port = 5432
database_name = 'WorldBank_db'
rds_connection_string = f'{protocol}://{username}:{password}@{host}:{port}/{database_name}'
engine = create_engine(rds_connection_string)